<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="MAIN" Id="{b9d23d5e-bdcb-4017-9242-a3dd838997b7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	myBoolean : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(* Modbus receive *)
//p_ModbusRx_OutputReg();
p_ModbusRx_OutputCoils();
p_ModbusRx_PLCMemory();

p_XLegacyPLCModbus();

(* 	HARD-WIRED I/O UPDATE
	Update IO 
*)
p_EtherCATDiag();
p_SoftIOMap();

(* 	RESOLVE LOGIC
	Device Control & Monitoring 
*)

p_GaugeSup();
p_ValveSup();
//p_TurboSup();
p_MPSSup();

(* 	HARD-WIRED I/O UPDATE
	Update IO 
*)
p_SoftIOMap();

(* 	EPICS Tx UPDATE
	Modbus Map Receive
	IMPORTANT: This is the LAST subroutine to be called. 
*)
p_ModbusTx_InputCoils();
p_ModbusTx_OutputCoils();
p_ModbusTx_InputReg();
//p_ModbusTx_OutputReg();
p_ModbusTx_PLCMemory();

g_xFirstPass := FALSE; // set this false after the first pass]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="6" Count="36" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>